# Clippy configuration for Synaptic
avoid-breaking-exported-api = false
msrv = "1.70.0"

# Allowed lints (use sparingly)
type-complexity-threshold = 250
cognitive-complexity-threshold = 30
too-many-arguments-threshold = 8
too-many-lines-threshold = 150
