# Rustfmt configuration for Synaptic
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Import organization
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true

# Function formatting
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"

# String formatting
format_strings = true
format_macro_matchers = true

# Comment formatting
comment_width = 80
wrap_comments = true
normalize_comments = true

# Misc formatting
trailing_comma = "Vertical"
match_arm_trailing_comma = true
use_field_init_shorthand = true
use_try_shorthand = true

# Advanced formatting
condense_wildcard_suffixes = true
empty_item_single_line = true
enum_discrim_align_threshold = 0
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = true
hex_literal_case = "Preserve"
indent_style = "Block"
inline_attribute_width = 0
match_block_trailing_comma = false
merge_derives = true
newline_style = "Auto"
normalize_doc_attributes = true
overflow_delimited_expr = false
remove_nested_parens = true
reorder_impl_items = true
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 0
struct_lit_single_line = true
where_single_line = false
