blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/njfio/rust-synaptic/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Vulnerability
    url: https://github.com/njfio/rust-synaptic/security/advisories/new
    about: Report a security vulnerability (private)
