global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'synaptic-monitor'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

# Rule files (optional)
# rule_files:
#   - "alerts/*.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Synaptic application metrics
  # Uncomment and configure when running actual Synaptic application
  # - job_name: 'synaptic'
  #   static_configs:
  #     - targets: ['synaptic:9090']
  #   metrics_path: '/metrics'
  #   scrape_interval: 10s

  # PostgreSQL metrics (requires postgres_exporter)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres_exporter:9187']

  # Redis metrics (requires redis_exporter)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis_exporter:9121']

  # Node exporter for system metrics
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node_exporter:9100']
