# Comprehensive Benchmarking Configuration
# Performance targets and test scenarios for Synaptic AI Agent Memory System

[targets]
# Performance targets for validation
min_ops_per_second = 100_000
max_latency_ms = 10
max_memory_usage_mb = 2048
max_cpu_usage_percent = 80

[scenarios]
# Test scenario configurations

[scenarios.micro]
name = "Micro-benchmarks"
description = "Individual operation benchmarks"
memory_count = 10_000
content_size = 500
concurrent_operations = 10
batch_size = 100
iterations = 1000

[scenarios.integration]
name = "Integration benchmarks"
description = "End-to-end workflow benchmarks"
memory_count = 50_000
content_size = 1000
concurrent_operations = 50
batch_size = 500
iterations = 500

[scenarios.stress]
name = "Stress testing"
description = "High-load performance validation"
memory_count = 100_000
content_size = 2000
concurrent_operations = 200
batch_size = 1000
iterations = 100

[scenarios.real_world]
name = "Real-world simulation"
description = "Realistic usage patterns"
memory_count = 25_000
content_size = 750
concurrent_operations = 25
batch_size = 250
iterations = 200

[operations]
# Operation-specific configurations

[operations.store]
weight = 30  # 30% of operations
target_ops_per_second = 50_000
max_latency_ms = 5

[operations.retrieve]
weight = 40  # 40% of operations
target_ops_per_second = 80_000
max_latency_ms = 2

[operations.search]
weight = 20  # 20% of operations
target_ops_per_second = 10_000
max_latency_ms = 20

[operations.analytics]
weight = 10  # 10% of operations
target_ops_per_second = 1_000
max_latency_ms = 100

[memory_sizes]
# Different memory content sizes for testing
small = 100
medium = 500
large = 1000
xlarge = 2000
xxlarge = 5000

[concurrency_levels]
# Concurrency levels for testing
low = 10
medium = 50
high = 100
extreme = 200

[batch_sizes]
# Batch sizes for bulk operations
small = 100
medium = 500
large = 1000
xlarge = 2000

[reporting]
# Benchmark reporting configuration
output_format = "json"
include_system_info = true
include_detailed_metrics = true
generate_charts = true
export_csv = true

[thresholds]
# Performance thresholds for pass/fail
memory_operations_min_ops_per_sec = 50_000
analytics_operations_min_ops_per_sec = 5_000
security_operations_min_ops_per_sec = 10_000
concurrent_operations_min_ops_per_sec = 30_000
batch_operations_min_ops_per_sec = 40_000

[environment]
# Environment-specific settings
rust_log = "info"
tokio_worker_threads = 8
max_blocking_threads = 16
enable_tracing = false  # Disable for benchmarks
enable_metrics = false  # Disable for benchmarks
